defaults:
  - base

ckpt_load_path: /home/ahern/projects/aa_diffusion_data/models/rf2a_25c_414_t1d-114.pt

extra_tXd:
  - radius_of_gyration_v2
  - relative_sasa_v2
  - sinusoidal_timestep_embedding

extra_tXd_params:
  radius_of_gyration_v2:
    low: 10
    high: 100
    n_bins: 9
  relative_sasa_v2:
    low: 0
    high: 0.2
    n_bins: 3
  sinusoidal_timestep_embedding:
    embedding_dim: 20
    max_positions: 10000

rf:
  model:
    get_quaternion: true
    n_extra_block: 4
    n_main_block: 32
    n_ref_block: 4
    d_msa: 256
    d_msa_full: 64
    d_pair: 192
    d_templ: 64
    n_head_msa: 8
    n_head_pair: 6
    n_head_templ: 4
    d_hidden: 32
    d_hidden_templ: 64
    d_t1d: 114
    p_drop: 0.15
    SE3_param:
      num_layers: 1
      num_channels: 32
      num_degrees: 2
      n_heads: 4
      div: 4
      l0_in_features: 64
      l0_out_features: 64
      l1_in_features: 3
      l1_out_features: 2
      num_edge_features: 64
    SE3_ref_param:
      num_layers: 2
      num_channels: 32
      num_degrees: 2
      n_heads: 4
      div: 4
      l0_in_features: 64
      l0_out_features: 64
      l1_in_features: 3
      l1_out_features: 2
      num_edge_features: 64
    freeze_track_motif: true
    symmetrize_repeats: false
    repeat_length: None
    symmsub_k: None
    sym_method: mean
    copy_main_block_template: false
    main_block: None
    lj_lin: 0.75
    use_chiral_l1: true
    use_lj_l1: true
    use_atom_frames: true
    use_same_chain: true
    recycling_type: all
    enable_same_chain: true
    refiner_topk: 128
  ckpt_path: null